"""Level registry — all 60 levels active."""

from app.levels.handlers import HANDLERS

DIFF_MAP = [
    (range(1, 16), "easy"),
    (range(16, 31), "medium"),
    (range(31, 46), "hard"),
    (range(46, 56), "expert"),
    (range(56, 61), "insane"),
]

LEVEL_META = {
    1:  ("authentication logic", "Bypassing the authentication logic",
         "Announce yourself as the lord of the city",
         "Login as admin."),
    2:  ("authentication logic", "Bypassing Logic without Comments",
         "To pass the gates, you must not cut the rope of syntax; you must weave your own terms to complete the scroll.",
         "Comments are strictly blocked. You cannot erase the tailing query—you must close the quotes and balance the logic naturally."),
    3:  ("numeric logic", "Numeric Logic & Operator Bypass",
             "No quotes block your path, but pulling the whole crowd won't open the door; only the throne must respond.",
             "The input is unquoted. Comments are blocked, and fetching multiple rows fails. Balance the numeric logic to target only the admin."),
    4:  ("column enumeration", "Discovering Column Count with UNION",
             "Before you can carve the mark of edis into the scroll, you must measure the exact width of its columns.",
             "The goal is column enumeration. Find the exact column count using ORDER BY or UNION SELECT, then inject the string 'edis' into the matched columns."),
    5:  ("data type enumeration", "Matching Data Types with UNION",
             "The hall accepts the strength of words, yet a hidden pillar demands the weight of pure numbers. Place 1337 upon its true place.",
             "The query checks column types strictly. One of the fields requires a pure numeric payload 1337 while the others expect strings. Align the types correctly in your UNION SELECT statement."),
    6:  ("schema enumeration & comment bypass", "Extracting Table Names under Filtered Syntax",
             "The simple blades of silence are shattered at the gate; pass through the shadows of encoding and unveil the names of the hidden vaults.",
             "Standard comment operators are blocked. Bypass the syntax filter and query the database metadata to discover the target table name within the current database context."),
    7:  ("dynamic schema enumeration", "Bypassing Strict Output Constraints",
             "The vault's true identifier is masked behind random digits under the mark of CTF. Filter through the strict limits without triggering the alarm.",
             "Parentheses are strictly forbidden, preventing function calls, and retrieving too many rows at once will trigger a security block. The target table is prefixed with 'CTF_' and stored in a dynamic database—isolate its exact schema name using SQL pattern matching before extracting the flag."),
    8:  ("error-based extraction", "Leaking the Flag Through SQL Errors",
         "The mirror shows no faces, only cracks — and in every crack a secret whispers.",
         "UNION and normal row output will not help. Trigger a verbose SQL error (extractvalue/updatexml or similar) so the flag from secrets appears inside the error message."),
    9:  ("conditional if logic", "Extracting Secrets with IF()",
         "The door opens for many, yet the vault answers only those who speak in conditions.",
         "Direct UNION dumps of secrets.flag are rejected. Use IF(condition, true_expr, false_expr) so the true branch returns the flag from secrets into the result set."),
    10: ("boolean blind proof", "Length, Then the Sixth Glyph",
         "The oracle answers only yes or no — until you name the measure and the sixth mark.",
         "Response rows are hidden: only 'User exists' / 'User not found'. Use boolean conditions to learn LENGTH(flag) and SUBSTRING(flag,6,1). Then UNION SELECT that length and that single character as the two columns. Direct flag dumps are blocked."),
    11: ("budget binary search", "Twenty-Five Questions",
         "The vault keeps a number in the column named here — but you may only knock twenty-five times.",
         "secrets.here holds an integer in [1,300]. Each request costs 1 attempt . Use (SELECT here FROM secrets LIMIT 1). When sure, 1=0 UNION SELECT <number>, 'edis' to prove it. At 26 the number re-rolls."),
    12: ("String Length Extraction", "Find the length of the flag.",
         "Measure the shadow before chasing it.",
         "Compare LENGTH(flag) with a number via boolean channel."),
    13: ("Character Extraction", "Extract flag one character at a time.",
         "One letter at a time reveals the name.",
         "Use SUBSTRING/ORD conditions in the expression field."),
    14: ("Time-Based Intro", "Use time delays when there is little feedback.",
         "When the room stays quiet, wait and listen.",
         "SLEEP(n) inside a true branch; measure elapsed."),
    15: ("Basic Filter Bypass", "A simple keyword blacklist is in place.",
         "The guards only know a few forbidden words.",
         "Bypass with case, comments inside words, or encoding."),
    16: ("Union with Types", "Column types must align for UNION.",
         "Different materials cannot be joined easily.",
         "Use NULL or CAST to match types."),
    17: ("Union + Limit", "Only one row is returned.",
         "The window shows only the first traveler.",
         "Inject before LIMIT or use subquery tricks."),
    18: ("Second-Order Basic", "Payload is stored, then executed later.",
         "The poison is planted today, but kills tomorrow.",
         "password=save stores username; password=view triggers the query."),
    19: ("Cookie Injection", "Vulnerable value comes from a cookie-like field.",
         "The message is written on the traveler's token.",
         "Put the payload in username (simulates cookie)."),
    20: ("Header Injection", "User-Agent style header is trusted.",
         "Even the messenger's name is trusted.",
         "Inject via username field (simulates User-Agent)."),
    21: ("JSON Body SQLi", "Value from a JSON body is concatenated.",
         "The letter is sealed in a modern envelope.",
         "Same form field maps to the JSON user value."),
    22: ("Blind Time + Filter", "SLEEP is filtered; find another way or bypass.",
         "The clock is guarded by simple rules.",
         "Filter blocks sleep/benchmark — obfuscate or alternate."),
    23: ("Order By Injection", "ORDER BY clause is injectable.",
         "The sorting order can be controlled by outsiders.",
         "Inject into ORDER BY — CASE / boolean / error based."),
    24: ("Group By / Having", "HAVING is injectable.",
         "The gathering rules are weak.",
         "Put boolean or subquery into HAVING."),
    25: ("Stacked Queries", "Multiple statements may run.",
         "One order can contain many commands.",
         "Terminate with ; and append another statement."),
    26: ("Out-of-Band Surface", "Explore side-channel style extraction.",
         "Send a letter to a far kingdom and wait.",
         "Use error-based or alternative channels; classic SELECT still works."),
    27: ("WAF Simple Keywords", "Common SQLi keywords are blocked.",
         "The gatekeeper knows the common spells.",
         "Obfuscate: UN/**/ION, case mix, concatenation."),
    28: ("Double Encoding", "Input is URL-decoded once.",
         "The message is wrapped twice.",
         "Encode payloads so that after one decode they become SQLi."),
    29: ("Scientific Notation", "Spaces and quotes blocked on numeric id.",
         "Numbers can wear strange disguises.",
         "Inject without spaces/quotes into numeric context."),
    30: ("Inline Comments Bypass", "Whole-word blacklist on union/select.",
         "Words can be broken by silence inside them.",
         "UN/**/ION SEL/**/ECT style bypass."),
    31: ("Advanced Boolean Blind", "Minimal 0/1 response channel.",
         "The oracle answers in riddles of presence.",
         "Expression in IF(...) against secrets table."),
    32: ("Time-Based Heavy Filter", "Common delay functions blocked.",
         "The clocks have been silenced by decree.",
         "Find alternative delay or bypass the regex."),
    33: ("Second-Order Advanced", "Stored payload executes on view.",
         "The seed grows in a different season.",
         "save then view — second-order pattern."),
    34: ("WAF Regex Bypass", "Regex blocks classic patterns.",
         "The guardian uses patterns, not just words.",
         "Avoid union select / or 1=1 shapes; use alternatives."),
    35: ("No Error, No Time", "Response is always OK.",
         "Neither pain nor delay reveals the truth.",
         "Query still runs — think stacked/second-order/side effects."),
    36: ("INSERT Injection", "Injection inside INSERT values.",
         "You are writing in the book of records.",
         "Break out of VALUES and manipulate statement."),
    37: ("UPDATE Injection", "Injection inside UPDATE.",
         "You are rewriting an existing story.",
         "Inject in SET or WHERE via the two fields."),
    38: ("Limit & Offset Abuse", "LIMIT clause is injectable.",
         "You can only control how many and from where.",
         "Inject into LIMIT expression."),
    39: ("Prepared Statement Bypass", "Only part of the query is safe.",
         "The armor has a hidden crack.",
         "id is validated; username is still concatenated."),
    40: ("Quote Stripping", "Quotes are stripped from input.",
         "Quotes vanish before the query.",
         "Work without quotes — numeric / CHAR / hex techniques."),
    41: ("JSON + Dual Fields", "Two fields are both injectable.",
         "The letter has many sealed compartments.",
         "username and password both go into the query."),
    42: ("Header + Cookie Chain", "Two inputs combined with OR.",
         "Several messengers must agree.",
         "Either field can carry the injection."),
    43: ("Blind Extraction", "Yes/no only on secrets.",
         "The only way out is careful questions.",
         "Boolean expression against secrets."),
    44: ("Filter + Encoding Maze", "Spaces removed and keywords blocked.",
         "Every gate has a different lock.",
         "Bypass layered filters with comments and encoding."),
    45: ("Conditional Error Blind", "Errors only when condition is true.",
         "The trap only springs for the unworthy.",
         "IF(condition, error-subquery, 0)."),
    46: ("WAF + Obfuscation", "Classic patterns blocked.",
         "The poison must pass the guards.",
         "Obfuscate enough to slip past the regex."),
    47: ("Stacked + Filter", "Stacked allowed but DML keywords blocked.",
         "Many commands, but the language is restricted.",
         "Stack carefully without drop/delete/update/insert words."),
    48: ("No UNION Keyword", "The word UNION is blocked.",
         "The messenger cannot speak that word.",
         "Extract without UNION — error based / blind / stacked."),
    49: ("No Spaces", "All spaces are stripped.",
         "There is no room between the words.",
         "Use comments or parentheses instead of spaces."),
    50: ("No Comments", "SQL comments are forbidden.",
         "Silence itself is forbidden.",
         "Balance quotes without comment syntax."),
    51: ("Blind + Heavy WAF", "Strong keyword block + boolean only.",
         "The oracle is locked behind iron patterns.",
         "Bypass WAF then boolean-extract from secrets."),
    52: ("Polyglot Payload", "One payload, classic string context.",
         "One key must open several different doors.",
         "Craft clean extraction payload."),
    53: ("No Quotes Allowed", "Quotes rejected; numeric context.",
         "The scribes forbid certain symbols.",
         "Inject in numeric id context without quotes."),
    54: ("Bit-by-Bit Advanced", "Y/N channel for bit extraction.",
         "Each grain of sand must be counted separately.",
         "ASCII/bit conditions on flag characters."),
    55: ("Chained Contexts", "Second-order chain again.",
         "The river flows through different lands.",
         "save payload, then view to execute."),
    56: ("Full Chain Expert", "Keywords blocked unless obfuscated with comments.",
         "The final fortress has layered defenses.",
         "Use inline comments inside keywords."),
    57: ("Protocol Surface", "Classic injection with deep extraction.",
         "There are hidden roads not marked on the map.",
         "Error/union/blind — any path to secrets.flag."),
    58: ("Race Surface", "Same vulnerable login surface.",
         "Two actions at the same moment open a crack.",
         "Standard extraction applies."),
    59: ("Almost Impossible Filter", "Very limited character set.",
         "Almost every symbol is forbidden.",
         "Work inside the allowed charset."),
    60: ("The Final Gate", "union/select/schema/comments all blocked.",
         "Only those who mastered every path may enter.",
         "Bypass without banned tokens — creativity required."),
}


def get_diff(level_id: int) -> str:
    for r, d in DIFF_MAP:
        if level_id in r:
            return d
    return "easy"


def get_meta(level_id: int) -> dict:
    name, desc, hi, ht = LEVEL_META.get(
        level_id,
        (f"Level {level_id}", "Extract the flag.", "Observe.", "Inject."),
    )
    return {
        "id": level_id,
        "name": name,
        "diff": get_diff(level_id),
        "desc": desc,
        "hint_i": hi,
        "hint_t": ht,
        "implemented": level_id in HANDLERS,
    }


def handle_level(level_id: int, payload: dict) -> dict:
    fn = HANDLERS.get(level_id)
    if not fn:
        return {"ok": False, "error": "Level handler missing", "raw": ""}
    return fn(payload)


LEVEL_NAMES = {i: LEVEL_META[i][0] for i in LEVEL_META}
REGISTRY = HANDLERS
