"""Level registry — all 60 levels active."""

from app.levels.handlers import HANDLERS

DIFF_MAP = [
    (range(1, 16), "easy"),
    (range(16, 31), "medium"),
    (range(31, 46), "hard"),
    (range(46, 56), "expert"),
    (range(56, 61), "insane"),
]

LEVEL_META = {
    1:  ("Auth Bypass", "Bypass login and become admin.",
         "Announce yourself at the gate as the city's lord.",
         "Inject into the login query and authenticate as admin."),
    2:  ("No Comments", "Bypass auth without SQL comments.",
         "Do not cut the rope of syntax — weave it closed.",
         "Comments are blocked. Close quotes and balance AND/OR so the trailing condition still holds."),
    3:  ("Numeric Bypass", "Inject in an unquoted numeric context.",
         "No quotes guard this path; only the throne may answer.",
         "Input is unquoted. Multi-row dumps fail — target admin only without comments."),
    4:  ("Column Count", "Find the column count, then plant a marker.",
         "Measure the scroll before you carve your mark.",
         "Enumerate columns with ORDER BY or UNION, then inject the marker string 'edis' into matching columns."),
    5:  ("UNION Types", "Align column types in a UNION SELECT.",
         "Words and numbers must share the same hall.",
         "Match types across the UNION. One column expects the number 1337; others expect strings."),
    6:  ("Schema under Filter", "Bypass comment filters and list tables.",
         "Silence is broken at the gate — seek the names of the vaults.",
         "Standard comments are blocked. Reach metadata and discover table names in the current database and union select the table names."),
    7:  ("Constrained Schema", "Find the flag in a hidden schema — not the local secrets table.",
         "The vault was moved under a CTF mark; the old shelf only says NOT HERE.",
         "Comments and parentheses are blocked; keep result sets small (≤3 rows). Enumerate schemata/tables via information_schema, look for names tied to this level (prefix patterns), then read the flag column from that table. Close quotes without --."),
    8:  ("Error-Based", "Pull the flag out of a SQL error.",
         "The mirror shows no faces — only cracks that whisper secrets.",
         "Row dumps are hidden. Force an error (e.g. extractvalue/updatexml) that includes data from secrets."),
    9:  ("IF Extraction", "Return the flag through IF() logic.",
         "The vault answers only those who speak in conditions.",
         "Direct dumps of secrets.flag are rejected. Use IF(condition, true_expr, false_expr) to surface the flag."),
    10: ("Boolean Proof", "Prove length and the 6th character of the flag.",
         "The oracle answers only yes or no — until you name the sixth mark.",
         "Blind boolean channel only. Learn LENGTH(flag) and SUBSTRING(flag,6,1), then prove both via UNION with those literals."),
    11: ("Budget Search", "Binary-search secrets.here within 25 attempts.",
         "A number sleeps in 'here' — you may knock only twenty-five times.",
         "Compare against secrets.here with < > =. Dumping the column via UNION is blocked. Prove with UNION SELECT <n>, 'edis'."),
    12: ("ORD / SUBSTRING", "Match the 7th character via ORD/ASCII.",
         "Measure a single letter by its number.",
         "Use ORD/ASCII with SUBSTRING on flag (7th char). When the boolean is true, the flag is revealed."),
    13: ("Time + Proof", "Find the 12th character by timing, then prove it.",
         "Time speaks in silence; seal the twelfth mark with the word edis.",
         "Use time-based conditions to learn the 12th character, then UNION a proof row with that char and 'edis'."),
    14: ("Time Threshold", "Force a delay longer than one second.",
         "The clock must toll beyond a single breath.",
         "Row output is hidden. Trigger SLEEP (or similar) so the request takes more than 1 second."),
    15: ("Blacklist Bypass", "Open the WHERE clause despite a keyword blacklist.",
         "Common spells are banned at the gate — find another operator.",
         "union/select/or/and/comments are blocked. Bypass so the query matches multiple user rows."),
    16: ("Typed UNION", "Extract the flag with a type-aligned UNION.",
         "Different materials join only when shaped alike.",
         "UNION must match three columns (int, string, string). Use NULL/CAST if needed; avoid dumping the whole table."),
    17: ("UNION under LIMIT", "Inject past a fixed LIMIT 1.",
         "The window shows only the first traveler.",
         "LIMIT 1 is fixed after WHERE. Inject before it, or use subquery/UNION tricks to still extract the flag."),
    18: ("Second-Order", "Store a payload, then trigger it on view.",
         "Poison planted today strikes tomorrow.",
         "password=save stores username; password=view runs the unsafe read of that stored value."),
    19: ("Cookie Injection", "Inject through a cookie-like value.",
         "The traveler's token is trusted too far.",
         "The username field simulates a cookie. Inject there — plain 'admin' is not enough."),
    20: ("Header Injection", "Inject through a User-Agent-like field.",
         "Even the messenger's name is written into the query.",
         "username simulates User-Agent. Forge the header value with SQLi."),
    21: ("JSON Field SQLi", "Inject a value that came from a JSON body.",
         "The letter is sealed, yet still read aloud.",
         "Same form field maps to a JSON user value concatenated into SQL."),
    22: ("Time under Filter", "Cause a delay while SLEEP is filtered.",
         "The clock is guarded by simple rules.",
         "SLEEP/BENCHMARK strings are filtered. Obfuscate them or find another slow path (>1.5s)."),
    23: ("ORDER BY Injection", "Abuse an injectable ORDER BY clause.",
         "Outsiders should not decide the order of the scroll.",
         "Inject into ORDER BY — CASE/boolean/error or subquery toward secrets."),
    24: ("HAVING Injection", "Inject into a HAVING clause.",
         "The rules of the gathering are weak.",
         "Put boolean logic or a subquery into HAVING to reach secrets."),
    25: ("Stacked Queries", "Run a second statement after the first.",
         "One order may hide many commands.",
         "Terminate with ; and append another SELECT (e.g. against secrets). Avoid dumping users."),
    26: ("Side-Channel Surface", "Prefer error-based extraction; OUTFILE is closed.",
         "Letters to far kingdoms never leave this lab.",
         "OUTFILE/LOAD_FILE are disabled. Use error-based or a tight query to reach the flag."),
    27: ("Keyword WAF", "Bypass a whole-word keyword blacklist.",
         "The gatekeeper knows the common spells by name.",
         "Bare union/select/or/... are blocked. Split keywords with inline comments (UN/**/ION)."),
    28: ("Double Encoding", "Survive a single URL-decode layer.",
         "The message is wrapped once before it is read.",
         "Input is URL-decoded once. Encode special characters so they become SQLi only after that decode."),
    29: ("Numeric Tricks", "Inject into id without spaces or quotes.",
         "Numbers can wear strange disguises.",
         "No spaces, quotes, or semicolons. Use operators without spaces (e.g. 1OR1=1) or similar tricks."),
    30: ("Inline Comments", "Split blacklisted keywords with /* */.",
         "Silence between the letters opens the gate.",
         "Whole-word blacklist is active. Break keywords with inline comments so the WAF misses them."),
    31: ("Boolean Channel", "Ask yes/no questions against secrets.",
         "The oracle answers only with presence or absence.",
         "Expression is wrapped in IF(...) on secrets. Bitwise/boolean extract; prove the full flag to clear."),
    32: ("Filtered Time", "Delay the query without common sleep functions.",
         "The usual clocks have been silenced by decree.",
         "sleep/benchmark/get_lock-style tokens are blocked. Find another way to exceed ~1.5s."),
    33: ("Second-Order II", "Again: store first, execute on view.",
         "The seed waits a season before it grows.",
         "password=save then password=view on an isolated DB. Extract secrets on the second step."),
    34: ("Regex WAF", "Avoid patterns the regex is watching for.",
         "The guardian matches shapes, not only words.",
         "Classic 'union select' and 'or 1=1' shapes are blocked. Use alternate syntax."),
    35: ("Silent Result", "No errors and no timing feedback.",
         "Neither pain nor delay will answer you.",
         "Response is always OK. Use stacked side-effects (e.g. write a marker) to prove control."),
    36: ("INSERT Injection", "Break out of an INSERT VALUES list.",
         "You are writing into the book of records.",
         "Inject in username/email values to change role or extract via the statement."),
    37: ("UPDATE Injection", "Inject in SET or WHERE of an UPDATE.",
         "You are rewriting a line already written.",
         "username and password fields feed SET/WHERE. Escalate or hit admin without dumping."),
    38: ("LIMIT Injection", "Abuse an injectable LIMIT expression.",
         "You only choose how many, and from where — or so they think.",
         "Inject into LIMIT. Subqueries can still reach secrets; keep results small."),
    39: ("Partial Prepared", "One parameter is safe; the other is not.",
         "The armor covers the chest but not the side.",
         "id is validated as an integer. username is still concatenated — attack that side."),
    40: ("Quote Stripping", "Quotes are removed before the query runs.",
         "Every quote vanishes on the threshold.",
         "Work after quotes are stripped — OR/UNION shapes that do not depend on keeping a leading quote."),
    41: ("Dual Fields", "Both username and password are injectable.",
         "The letter has more than one sealed fold.",
         "Both fields enter the WHERE clause. Inject on either side of the AND."),
    42: ("OR Chain", "Two inputs combined with OR.",
         "Either messenger may carry the key.",
         "username OR password — one injected field is enough."),
    43: ("Blind on Secrets", "Yes/no answers from the secrets table.",
         "Only careful questions leave this room.",
         "Boolean expression against secrets. Prove the full flag when you know it."),
    44: ("Layered Filters", "Spaces stripped and keywords blocked.",
         "Each gate turns a different key.",
         "Spaces are removed and keywords filtered. Use /**/ (and similar) so keywords are not contiguous."),
    45: ("Conditional Error", "Errors fire only when your condition is true.",
         "The trap springs only for the right footstep.",
         "Shape IF(condition, error-expr, 0). True conditions surface errors; use that to confirm the flag."),
    46: ("WAF Obfuscation", "Classic patterns are regex-blocked.",
         "The poison must change shape to pass the guards.",
         "Bare 'union select' and 'or 1=1' are blocked. Obfuscate and extract the flag."),
    47: ("Stacked + DML Filter", "Stack queries without dangerous keywords.",
         "Many commands are allowed — a few words are not.",
         "Stack with ; but drop/delete/update/insert (and friends) are blocked. SELECT the flag."),
    48: ("No UNION Word", "The keyword UNION is forbidden.",
         "That word may not be spoken here.",
         "Extract without UNION — error-based, blind, or stacked SELECT."),
    49: ("No Spaces", "Every space is stripped from your input.",
         "There is no gap between the words.",
         "Build the payload without relying on spaces (/**/, parentheses, etc.)."),
    50: ("No Comment Syntax", "SQL comments are rejected entirely.",
         "Even silence is forbidden at this gate.",
         "No --, #, or /* */. Close quotes and balance the trailing AND role='user'."),
    51: ("Blind under WAF", "Heavy keyword block plus boolean-only output.",
         "The oracle sits behind iron patterns.",
         "Bypass the WAF, then boolean-extract from secrets and prove the flag."),
    52: ("Clean Extraction", "One precise payload in a classic string context.",
         "One key should open the lock cleanly.",
         "String SQLi as usual — extract secrets.flag without dumping the whole table."),
    53: ("No Quotes (Numeric)", "Quotes are rejected; id is numeric.",
         "The scribes will not write quotation marks.",
         "Inject into WHERE id = {input} without any quotes."),
    54: ("Bit Channel", "Y/N answers for bit or ASCII tests.",
         "Each grain of sand is counted alone.",
         "Boolean/bit conditions on flag characters (Y/N). Prove the full flag when ready."),
    55: ("Second-Order Chain", "Store on save, execute on view.",
         "The river carries your words to another shore.",
         "password=save stores the payload; password=view runs the second-order query."),
    56: ("Comment-Split Keywords", "Keywords allowed only if split with comments.",
         "The fortress reads whole words — not broken ones.",
         "Bare union/select/or are blocked. Split them with /* */ (e.g. UN/**/ION)."),
    57: ("Open Surface", "Any classic path to secrets.flag.",
         "Hidden roads still lead to the same vault.",
         "Error, UNION, or blind — reach secrets.flag. OUTFILE is disabled."),
    58: ("Login Surface", "Classic injectable login query.",
         "The ledger trusts both name and password too much.",
         "Inject on username and/or password. Plain admin without injection does not clear the level."),
    59: ("Strict Charset", "Only a small character set is allowed.",
         "Almost every symbol is turned away.",
         "Allowed: letters, digits, _, space, quotes, and -|=<> . No ; () or comments."),
    60: ("Final Gate", "union, select, schema, and comments are blocked.",
         "Only those who mastered every path may enter.",
         "No union/select/information_schema/comments. Balance quotes and boolean logic past role='user'."),
}



def get_diff(level_id: int) -> str:
    for r, d in DIFF_MAP:
        if level_id in r:
            return d
    return "easy"


def get_meta(level_id: int) -> dict:
    name, desc, hi, ht = LEVEL_META.get(
        level_id,
        (f"Level {level_id}", "Extract the flag.", "Observe.", "Inject."),
    )
    return {
        "id": level_id,
        "name": name,
        "diff": get_diff(level_id),
        "desc": desc,
        "hint_i": hi,
        "hint_t": ht,
        "implemented": level_id in HANDLERS,
    }


def handle_level(level_id: int, payload: dict) -> dict:
    fn = HANDLERS.get(level_id)
    if not fn:
        return {"ok": False, "error": "Level handler missing", "raw": ""}
    return fn(payload)


LEVEL_NAMES = {i: LEVEL_META[i][0] for i in LEVEL_META}
REGISTRY = HANDLERS
